spring:
  application:
    name: cas-core

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

    jpa:
      hibernate:
        ddl-auto: validate

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    table: schema_version