server:
  port: 8080

spring:
  application:
    name: cas-core

  datasource:
    url: jdbc:postgresql://localhost:5432/cas-database
    username: cas-admin
    password: cas123!

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    web:
      pageable:
        default-page-size: 64

  flyway:
    url: jdbc:postgresql://localhost:5432/cas-database
    user: cas-admin
    password: cas123!
    table: schema_version

cas:
  security:
    jwt:
      secret: 656uzf9s3JhPGu1HSj6nkhV8-Jc-TH43C5Wd5p_BH9Zfbq03n4hWMFlskVP6_tZScNWBOmUAmNxgPVTuOmv6lw