server:
  port: 8081

spring:
  application:
    name: cas-authorizer

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
